import sys

try:
    something
except OSError as err:
    print(f"Error: {err}")
    sys.exit(1)

Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      sqlite3.OperationalError: no such table: hosts

>>> hostping.hostPing('192.168.1.102')
b'PING 192.168.1.102 (192.168.1.102) 56(84) bytes of data.\nFrom 192.168.1.21 icmp_seq=1 Destination Host Unreachable\n\n--- 192.168.1.102 ping statistics ---\n1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms\n\n'
>>> hostping.hostPing('192.168.1.99')
b'PING 192.168.1.99 (192.168.1.99) 56(84) bytes of data.\n64 bytes from 192.168.1.99: icmp_seq=1 ttl=64 time=0.305 ms\n\n--- 192.168.1.99 ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss, time 0ms\nrtt min/avg/max/mdev = 0.305/0.305/0.305/0.000 ms\n'

